name: Deploy Daily Builds

# For testing
on: push

# For production
# on:
#   schedule:
#     - cron: "0 4 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: "yarn install"
      - run: "yarn compile"

      # Shipit
      - uses: orta/monorepo-deploy-nightly@master
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}